# Generated by Django 5.2.7 on 2026-05-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clasp_type',
            field=models.CharField(blank=True, choices=[('screw', 'Винтовая муфта'), ('auto', 'Автомуфта'), ('bayonet', 'Байонетная'), ('none', 'Без муфты')], max_length=20, verbose_name='Тип застёжки'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='load_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Грузоподъёмность (кг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='strength_class',
            field=models.CharField(blank=True, choices=[('basic', 'Базовый'), ('intermediate', 'Средний'), ('professional', 'Профессиональный'), ('expert', 'Экспертный')], max_length=20, verbose_name='Класс прочности'),
        ),
        migrations.AddField(
            model_name='product',
            name='temp_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. температура (°C)'),
        ),
        migrations.AddField(
            model_name='product',
            name='temp_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мин. температура (°C)'),
        ),
    ]
