# Generated by Django 5.2.7 on 2026-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_paid_order_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('online', 'Онлайн оплата (ЮMoney)')], default='cash', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
